// PlayerNetPackOpcodes.h

HandleOpcode(CMSG_DUNGEON_ALL_INFO);
HandleOpcode(CMSG_DUNGEON_BUILD_BY_TOKEN);
HandleOpcode(CMSG_DUNGEON_BUILD_BY_SILVER);
HandleOpcode(CMSG_DUNGEON_LEVELUP);
HandleOpcode(CMSG_DUNGEON_CANE);
HandleOpcode(CMSG_DUNGEON_CANE_FAST_LEVELUP);
HandleOpcode(CMSG_DUNGEON_ESCAPE);
HandleOpcode(CMSG_DUNGEON_TRY_CANE);
