#pragma once

#define MAX_PLAYER_COUNTRY_ID 3     //常规国家最大ID
#define MONSTER_COUNTRY_ID 4        //蛮族国家ID
#define NEURRAL_COUNTRY_ID 5		//中立国家ID
#define NR_PLAYER_COUNTRY 3
#define CHARACTER_COUNT 31


const int Reward_Country_Exp[MAX_PLAYER_COUNTRY_ID] = {4, 3, 2};
////mail_proto表中的event_id
enum EVENT_TYPE_ID
{
	EVENT_TYPE_EXPLOIT				= 17,
	EVENT_TYPE_CURSADE				= 18,
	EVENT_TYPE_CROSS_SERVER			= 19,
	EVENT_TYPE_ACT_STAR_BOX			= 20, 
	EVENT_TYPE_SIGN_UP				= 21, 
	EVENT_TYPE_GROUP_QUEST			= 22,
	EVENT_TYPE_ACT_IRON_COLLECT		= 23, 
	EVENT_TYPE_PASS_STAGE			= 24,
	EVENT_TYPE_XILIAN				= 25,
	EVENT_TYPE_CONTIN_OCCUPY_CITY	= 26,
	EVENT_TYPE_ACT_RECHARGE_REBATE	= 27,
	EVENT_TYPE_ACT_CELEBRITY		= 28,
	EVENT_TYPE_COUNTRY_OCCUPY_RANK	= 31,
	EVENT_TYPE_PERSONAL_OCCUPATION	= 29,
	EVENT_TYPE_ADD_SOLDIER			= 30,
	EVENT_TYPE_MILITARY_POWER_RANK  = 32,
	EVENT_TYPE_CONGRATULATE		    = 33,
};

#define STRING_UI_CONTINUE_OCCUPY_CITY	37303
#define STRING_UI_MONSTER_INVADE		11342
#define STRING_UI_MAN_COUNTRY_NAME		14103
#define STRING_UI_WORM_COUNTRY_NAME     14105
#define STRING_UI_GOD_COUNTRY_NAME		14104
enum
{
	CONGRATULATE_TYPE_SHENQI = 6,
	CONGRATULATE_TYPE_SUIT   = 5,
};


enum 
{
	SUIT_PRI_ITEM_ID_BASE = 1060000,
	SUIT_PRI_ITEM_ID_MAX  = 1060009,
	SUIT_MID_ITEM_ID_BASE = 1060100,
	SUIT_MID_ITEM_ID_MAX  = 1060104,
	SUIT_ADV_ITEM_ID_BASE = 1060200,
	SUIT_ADV_ITEM_ID_MAX  = 1060204,
	TYPE_SUIT_PRI_COUNT = SUIT_PRI_ITEM_ID_MAX - SUIT_PRI_ITEM_ID_BASE + 1,
	TYPE_SUIT_MID_COUNT = SUIT_MID_ITEM_ID_MAX - SUIT_MID_ITEM_ID_BASE + 1,
	TYPE_SUIT_ADV_COUNT = SUIT_ADV_ITEM_ID_MAX - SUIT_ADV_ITEM_ID_BASE + 1,
	TYPE_CONGRATULATE_SHEN_QI_COUNT = 4,
	CONGRATULATE_SHEN_QI_LEVEL_80 = 80,
	CONGRATULATE_SHEN_QI_LEVEL_100 = 100,
	CONGRATULATE_SHEN_QI_LEVEL_120 = 120,
	CONGRATULATE_SHEN_QI_LEVEL_150 = 150,
	CONGRATULATE_SHEN_QI_LEVEL_BASE = CONGRATULATE_SHEN_QI_LEVEL_80,
};
