//GameServerSession.cpp中实现函数体

Msg_Declare(SG2D_COUNTRY_BASE, CountyInfo)
Msg_Declare(SG2D_COUNTRY_ADD_CITY, Struct_City_Info)
Msg_Declare(SG2D_COUNTRY_DEL_CITY, Struct_City_Info)
Msg_Declare(SG2D_COUNTRY_ALL_INFO, SD2G_Country_AllInfo)
Msg_Declare(SG2D_COUNTRY_LEVLE_UP_TASK_RANK, Country_Levle_Up_Task_Rank)

Msg_Declare(SG2D_PALACE_ALL_INFO, GS2C_Palace_All_Info)
Msg_Declare(SG2D_ACTIVITY_COUNTRY_OCCUPY_CITY_UPDATE,Activity_Occupy_City_Num)
