// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Module.proto

#ifndef PROTOBUF_Module_2eproto__INCLUDED
#define PROTOBUF_Module_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Module_2eproto();
void protobuf_AssignDesc_Module_2eproto();
void protobuf_ShutdownFile_Module_2eproto();

class GxDB_Module;
class GxDB_Building;
class GxDB_Modules_Info;
class GxDB_Buildings_Info;
class C2GS_Building_State;
class GS2C_Building_State;
class C2GS_Building_Level_Up;
class GS2C_Building_Level_Up_Begin;
class GS2C_Building_Level_Up_Begin_lv_up_info;
class GS2C_Building_Level_Up;
class GS2C_Building_Gold_Hammer;
class GS2C_Module_Buy_Gain_Mode_Res;
class GS2C_Building_Update;

// ===================================================================

class GxDB_Module : public ::google::protobuf::Message {
 public:
  GxDB_Module();
  virtual ~GxDB_Module();

  GxDB_Module(const GxDB_Module& from);

  inline GxDB_Module& operator=(const GxDB_Module& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GxDB_Module& default_instance();

  void Swap(GxDB_Module* other);

  // implements Message ----------------------------------------------

  GxDB_Module* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GxDB_Module& from);
  void MergeFrom(const GxDB_Module& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 module_id = 1;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // optional uint32 gain_mode = 2;
  inline bool has_gain_mode() const;
  inline void clear_gain_mode();
  static const int kGainModeFieldNumber = 2;
  inline ::google::protobuf::uint32 gain_mode() const;
  inline void set_gain_mode(::google::protobuf::uint32 value);

  // optional uint64 expire_time = 3;
  inline bool has_expire_time() const;
  inline void clear_expire_time();
  static const int kExpireTimeFieldNumber = 3;
  inline ::google::protobuf::uint64 expire_time() const;
  inline void set_expire_time(::google::protobuf::uint64 value);

  // optional bool is_rebuild = 4;
  inline bool has_is_rebuild() const;
  inline void clear_is_rebuild();
  static const int kIsRebuildFieldNumber = 4;
  inline bool is_rebuild() const;
  inline void set_is_rebuild(bool value);

  // optional uint64 gain_start_time = 5;
  inline bool has_gain_start_time() const;
  inline void clear_gain_start_time();
  static const int kGainStartTimeFieldNumber = 5;
  inline ::google::protobuf::uint64 gain_start_time() const;
  inline void set_gain_start_time(::google::protobuf::uint64 value);

  // optional uint32 gain_value = 6;
  inline bool has_gain_value() const;
  inline void clear_gain_value();
  static const int kGainValueFieldNumber = 6;
  inline ::google::protobuf::uint32 gain_value() const;
  inline void set_gain_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.GxDB_Module)
 private:
  inline void set_has_module_id();
  inline void clear_has_module_id();
  inline void set_has_gain_mode();
  inline void clear_has_gain_mode();
  inline void set_has_expire_time();
  inline void clear_has_expire_time();
  inline void set_has_is_rebuild();
  inline void clear_has_is_rebuild();
  inline void set_has_gain_start_time();
  inline void clear_has_gain_start_time();
  inline void set_has_gain_value();
  inline void clear_has_gain_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 module_id_;
  ::google::protobuf::uint32 gain_mode_;
  ::google::protobuf::uint64 expire_time_;
  ::google::protobuf::uint64 gain_start_time_;
  bool is_rebuild_;
  ::google::protobuf::uint32 gain_value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GxDB_Module* default_instance_;
};
// -------------------------------------------------------------------

class GxDB_Building : public ::google::protobuf::Message {
 public:
  GxDB_Building();
  virtual ~GxDB_Building();

  GxDB_Building(const GxDB_Building& from);

  inline GxDB_Building& operator=(const GxDB_Building& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GxDB_Building& default_instance();

  void Swap(GxDB_Building* other);

  // implements Message ----------------------------------------------

  GxDB_Building* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GxDB_Building& from);
  void MergeFrom(const GxDB_Building& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 building_id = 1;
  inline bool has_building_id() const;
  inline void clear_building_id();
  static const int kBuildingIdFieldNumber = 1;
  inline ::google::protobuf::uint32 building_id() const;
  inline void set_building_id(::google::protobuf::uint32 value);

  // optional uint32 building_lv = 2;
  inline bool has_building_lv() const;
  inline void clear_building_lv();
  static const int kBuildingLvFieldNumber = 2;
  inline ::google::protobuf::uint32 building_lv() const;
  inline void set_building_lv(::google::protobuf::uint32 value);

  // optional uint64 lvup_start_time = 3;
  inline bool has_lvup_start_time() const;
  inline void clear_lvup_start_time();
  static const int kLvupStartTimeFieldNumber = 3;
  inline ::google::protobuf::uint64 lvup_start_time() const;
  inline void set_lvup_start_time(::google::protobuf::uint64 value);

  // optional bool is_rebuild = 4;
  inline bool has_is_rebuild() const;
  inline void clear_is_rebuild();
  static const int kIsRebuildFieldNumber = 4;
  inline bool is_rebuild() const;
  inline void set_is_rebuild(bool value);

  // @@protoc_insertion_point(class_scope:pb.GxDB_Building)
 private:
  inline void set_has_building_id();
  inline void clear_has_building_id();
  inline void set_has_building_lv();
  inline void clear_has_building_lv();
  inline void set_has_lvup_start_time();
  inline void clear_has_lvup_start_time();
  inline void set_has_is_rebuild();
  inline void clear_has_is_rebuild();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 building_id_;
  ::google::protobuf::uint32 building_lv_;
  ::google::protobuf::uint64 lvup_start_time_;
  bool is_rebuild_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GxDB_Building* default_instance_;
};
// -------------------------------------------------------------------

class GxDB_Modules_Info : public ::google::protobuf::Message {
 public:
  GxDB_Modules_Info();
  virtual ~GxDB_Modules_Info();

  GxDB_Modules_Info(const GxDB_Modules_Info& from);

  inline GxDB_Modules_Info& operator=(const GxDB_Modules_Info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GxDB_Modules_Info& default_instance();

  void Swap(GxDB_Modules_Info* other);

  // implements Message ----------------------------------------------

  GxDB_Modules_Info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GxDB_Modules_Info& from);
  void MergeFrom(const GxDB_Modules_Info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb.GxDB_Module module_arr = 1;
  inline int module_arr_size() const;
  inline void clear_module_arr();
  static const int kModuleArrFieldNumber = 1;
  inline const ::pb::GxDB_Module& module_arr(int index) const;
  inline ::pb::GxDB_Module* mutable_module_arr(int index);
  inline ::pb::GxDB_Module* add_module_arr();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Module >&
      module_arr() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Module >*
      mutable_module_arr();

  // @@protoc_insertion_point(class_scope:pb.GxDB_Modules_Info)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Module > module_arr_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GxDB_Modules_Info* default_instance_;
};
// -------------------------------------------------------------------

class GxDB_Buildings_Info : public ::google::protobuf::Message {
 public:
  GxDB_Buildings_Info();
  virtual ~GxDB_Buildings_Info();

  GxDB_Buildings_Info(const GxDB_Buildings_Info& from);

  inline GxDB_Buildings_Info& operator=(const GxDB_Buildings_Info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GxDB_Buildings_Info& default_instance();

  void Swap(GxDB_Buildings_Info* other);

  // implements Message ----------------------------------------------

  GxDB_Buildings_Info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GxDB_Buildings_Info& from);
  void MergeFrom(const GxDB_Buildings_Info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb.GxDB_Building building_arr = 1;
  inline int building_arr_size() const;
  inline void clear_building_arr();
  static const int kBuildingArrFieldNumber = 1;
  inline const ::pb::GxDB_Building& building_arr(int index) const;
  inline ::pb::GxDB_Building* mutable_building_arr(int index);
  inline ::pb::GxDB_Building* add_building_arr();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >&
      building_arr() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >*
      mutable_building_arr();

  // @@protoc_insertion_point(class_scope:pb.GxDB_Buildings_Info)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building > building_arr_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GxDB_Buildings_Info* default_instance_;
};
// -------------------------------------------------------------------

class C2GS_Building_State : public ::google::protobuf::Message {
 public:
  C2GS_Building_State();
  virtual ~C2GS_Building_State();

  C2GS_Building_State(const C2GS_Building_State& from);

  inline C2GS_Building_State& operator=(const C2GS_Building_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2GS_Building_State& default_instance();

  void Swap(C2GS_Building_State* other);

  // implements Message ----------------------------------------------

  C2GS_Building_State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2GS_Building_State& from);
  void MergeFrom(const C2GS_Building_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 module_id = 1;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.C2GS_Building_State)
 private:
  inline void set_has_module_id();
  inline void clear_has_module_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 module_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static C2GS_Building_State* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_State : public ::google::protobuf::Message {
 public:
  GS2C_Building_State();
  virtual ~GS2C_Building_State();

  GS2C_Building_State(const GS2C_Building_State& from);

  inline GS2C_Building_State& operator=(const GS2C_Building_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_State& default_instance();

  void Swap(GS2C_Building_State* other);

  // implements Message ----------------------------------------------

  GS2C_Building_State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_State& from);
  void MergeFrom(const GS2C_Building_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pb.GxDB_Module module = 1;
  inline bool has_module() const;
  inline void clear_module();
  static const int kModuleFieldNumber = 1;
  inline const ::pb::GxDB_Module& module() const;
  inline ::pb::GxDB_Module* mutable_module();
  inline ::pb::GxDB_Module* release_module();
  inline void set_allocated_module(::pb::GxDB_Module* module);

  // repeated .pb.GxDB_Building building_state = 2;
  inline int building_state_size() const;
  inline void clear_building_state();
  static const int kBuildingStateFieldNumber = 2;
  inline const ::pb::GxDB_Building& building_state(int index) const;
  inline ::pb::GxDB_Building* mutable_building_state(int index);
  inline ::pb::GxDB_Building* add_building_state();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >&
      building_state() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >*
      mutable_building_state();

  // optional uint32 remain_auto_times = 3;
  inline bool has_remain_auto_times() const;
  inline void clear_remain_auto_times();
  static const int kRemainAutoTimesFieldNumber = 3;
  inline ::google::protobuf::uint32 remain_auto_times() const;
  inline void set_remain_auto_times(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_State)
 private:
  inline void set_has_module();
  inline void clear_has_module();
  inline void set_has_remain_auto_times();
  inline void clear_has_remain_auto_times();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pb::GxDB_Module* module_;
  ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building > building_state_;
  ::google::protobuf::uint32 remain_auto_times_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_State* default_instance_;
};
// -------------------------------------------------------------------

class C2GS_Building_Level_Up : public ::google::protobuf::Message {
 public:
  C2GS_Building_Level_Up();
  virtual ~C2GS_Building_Level_Up();

  C2GS_Building_Level_Up(const C2GS_Building_Level_Up& from);

  inline C2GS_Building_Level_Up& operator=(const C2GS_Building_Level_Up& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2GS_Building_Level_Up& default_instance();

  void Swap(C2GS_Building_Level_Up* other);

  // implements Message ----------------------------------------------

  C2GS_Building_Level_Up* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2GS_Building_Level_Up& from);
  void MergeFrom(const C2GS_Building_Level_Up& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool is_auto = 1;
  inline bool has_is_auto() const;
  inline void clear_is_auto();
  static const int kIsAutoFieldNumber = 1;
  inline bool is_auto() const;
  inline void set_is_auto(bool value);

  // optional uint32 building_id = 2;
  inline bool has_building_id() const;
  inline void clear_building_id();
  static const int kBuildingIdFieldNumber = 2;
  inline ::google::protobuf::uint32 building_id() const;
  inline void set_building_id(::google::protobuf::uint32 value);

  // optional uint32 module_id = 3;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 3;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.C2GS_Building_Level_Up)
 private:
  inline void set_has_is_auto();
  inline void clear_has_is_auto();
  inline void set_has_building_id();
  inline void clear_has_building_id();
  inline void set_has_module_id();
  inline void clear_has_module_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool is_auto_;
  ::google::protobuf::uint32 building_id_;
  ::google::protobuf::uint32 module_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static C2GS_Building_Level_Up* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_Level_Up_Begin_lv_up_info : public ::google::protobuf::Message {
 public:
  GS2C_Building_Level_Up_Begin_lv_up_info();
  virtual ~GS2C_Building_Level_Up_Begin_lv_up_info();

  GS2C_Building_Level_Up_Begin_lv_up_info(const GS2C_Building_Level_Up_Begin_lv_up_info& from);

  inline GS2C_Building_Level_Up_Begin_lv_up_info& operator=(const GS2C_Building_Level_Up_Begin_lv_up_info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_Level_Up_Begin_lv_up_info& default_instance();

  void Swap(GS2C_Building_Level_Up_Begin_lv_up_info* other);

  // implements Message ----------------------------------------------

  GS2C_Building_Level_Up_Begin_lv_up_info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_Level_Up_Begin_lv_up_info& from);
  void MergeFrom(const GS2C_Building_Level_Up_Begin_lv_up_info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 building_id = 1;
  inline bool has_building_id() const;
  inline void clear_building_id();
  static const int kBuildingIdFieldNumber = 1;
  inline ::google::protobuf::uint32 building_id() const;
  inline void set_building_id(::google::protobuf::uint32 value);

  // optional uint64 lvup_start_time = 2;
  inline bool has_lvup_start_time() const;
  inline void clear_lvup_start_time();
  static const int kLvupStartTimeFieldNumber = 2;
  inline ::google::protobuf::uint64 lvup_start_time() const;
  inline void set_lvup_start_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_Level_Up_Begin.lv_up_info)
 private:
  inline void set_has_building_id();
  inline void clear_has_building_id();
  inline void set_has_lvup_start_time();
  inline void clear_has_lvup_start_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 lvup_start_time_;
  ::google::protobuf::uint32 building_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_Level_Up_Begin_lv_up_info* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_Level_Up_Begin : public ::google::protobuf::Message {
 public:
  GS2C_Building_Level_Up_Begin();
  virtual ~GS2C_Building_Level_Up_Begin();

  GS2C_Building_Level_Up_Begin(const GS2C_Building_Level_Up_Begin& from);

  inline GS2C_Building_Level_Up_Begin& operator=(const GS2C_Building_Level_Up_Begin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_Level_Up_Begin& default_instance();

  void Swap(GS2C_Building_Level_Up_Begin* other);

  // implements Message ----------------------------------------------

  GS2C_Building_Level_Up_Begin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_Level_Up_Begin& from);
  void MergeFrom(const GS2C_Building_Level_Up_Begin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GS2C_Building_Level_Up_Begin_lv_up_info lv_up_info;

  // accessors -------------------------------------------------------

  // optional uint32 module_id = 1;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // optional uint32 remain_auto_times = 2;
  inline bool has_remain_auto_times() const;
  inline void clear_remain_auto_times();
  static const int kRemainAutoTimesFieldNumber = 2;
  inline ::google::protobuf::uint32 remain_auto_times() const;
  inline void set_remain_auto_times(::google::protobuf::uint32 value);

  // repeated .pb.GS2C_Building_Level_Up_Begin.lv_up_info build_state = 3;
  inline int build_state_size() const;
  inline void clear_build_state();
  static const int kBuildStateFieldNumber = 3;
  inline const ::pb::GS2C_Building_Level_Up_Begin_lv_up_info& build_state(int index) const;
  inline ::pb::GS2C_Building_Level_Up_Begin_lv_up_info* mutable_build_state(int index);
  inline ::pb::GS2C_Building_Level_Up_Begin_lv_up_info* add_build_state();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up_Begin_lv_up_info >&
      build_state() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up_Begin_lv_up_info >*
      mutable_build_state();

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_Level_Up_Begin)
 private:
  inline void set_has_module_id();
  inline void clear_has_module_id();
  inline void set_has_remain_auto_times();
  inline void clear_has_remain_auto_times();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 module_id_;
  ::google::protobuf::uint32 remain_auto_times_;
  ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up_Begin_lv_up_info > build_state_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_Level_Up_Begin* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_Level_Up : public ::google::protobuf::Message {
 public:
  GS2C_Building_Level_Up();
  virtual ~GS2C_Building_Level_Up();

  GS2C_Building_Level_Up(const GS2C_Building_Level_Up& from);

  inline GS2C_Building_Level_Up& operator=(const GS2C_Building_Level_Up& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_Level_Up& default_instance();

  void Swap(GS2C_Building_Level_Up* other);

  // implements Message ----------------------------------------------

  GS2C_Building_Level_Up* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_Level_Up& from);
  void MergeFrom(const GS2C_Building_Level_Up& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 building_id = 1;
  inline bool has_building_id() const;
  inline void clear_building_id();
  static const int kBuildingIdFieldNumber = 1;
  inline ::google::protobuf::uint32 building_id() const;
  inline void set_building_id(::google::protobuf::uint32 value);

  // required uint32 module_id = 2;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 2;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // required uint32 building_lv = 3;
  inline bool has_building_lv() const;
  inline void clear_building_lv();
  static const int kBuildingLvFieldNumber = 3;
  inline ::google::protobuf::uint32 building_lv() const;
  inline void set_building_lv(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_Level_Up)
 private:
  inline void set_has_building_id();
  inline void clear_has_building_id();
  inline void set_has_module_id();
  inline void clear_has_module_id();
  inline void set_has_building_lv();
  inline void clear_has_building_lv();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 building_id_;
  ::google::protobuf::uint32 module_id_;
  ::google::protobuf::uint32 building_lv_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_Level_Up* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_Gold_Hammer : public ::google::protobuf::Message {
 public:
  GS2C_Building_Gold_Hammer();
  virtual ~GS2C_Building_Gold_Hammer();

  GS2C_Building_Gold_Hammer(const GS2C_Building_Gold_Hammer& from);

  inline GS2C_Building_Gold_Hammer& operator=(const GS2C_Building_Gold_Hammer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_Gold_Hammer& default_instance();

  void Swap(GS2C_Building_Gold_Hammer* other);

  // implements Message ----------------------------------------------

  GS2C_Building_Gold_Hammer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_Gold_Hammer& from);
  void MergeFrom(const GS2C_Building_Gold_Hammer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb.GS2C_Building_Level_Up building_lv_up = 1;
  inline int building_lv_up_size() const;
  inline void clear_building_lv_up();
  static const int kBuildingLvUpFieldNumber = 1;
  inline const ::pb::GS2C_Building_Level_Up& building_lv_up(int index) const;
  inline ::pb::GS2C_Building_Level_Up* mutable_building_lv_up(int index);
  inline ::pb::GS2C_Building_Level_Up* add_building_lv_up();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up >&
      building_lv_up() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up >*
      mutable_building_lv_up();

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_Gold_Hammer)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up > building_lv_up_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_Gold_Hammer* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Module_Buy_Gain_Mode_Res : public ::google::protobuf::Message {
 public:
  GS2C_Module_Buy_Gain_Mode_Res();
  virtual ~GS2C_Module_Buy_Gain_Mode_Res();

  GS2C_Module_Buy_Gain_Mode_Res(const GS2C_Module_Buy_Gain_Mode_Res& from);

  inline GS2C_Module_Buy_Gain_Mode_Res& operator=(const GS2C_Module_Buy_Gain_Mode_Res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Module_Buy_Gain_Mode_Res& default_instance();

  void Swap(GS2C_Module_Buy_Gain_Mode_Res* other);

  // implements Message ----------------------------------------------

  GS2C_Module_Buy_Gain_Mode_Res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Module_Buy_Gain_Mode_Res& from);
  void MergeFrom(const GS2C_Module_Buy_Gain_Mode_Res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 error_code() const;
  inline void set_error_code(::google::protobuf::uint32 value);

  // optional .pb.GxDB_Module module_Info = 2;
  inline bool has_module_info() const;
  inline void clear_module_info();
  static const int kModuleInfoFieldNumber = 2;
  inline const ::pb::GxDB_Module& module_info() const;
  inline ::pb::GxDB_Module* mutable_module_info();
  inline ::pb::GxDB_Module* release_module_info();
  inline void set_allocated_module_info(::pb::GxDB_Module* module_info);

  // @@protoc_insertion_point(class_scope:pb.GS2C_Module_Buy_Gain_Mode_Res)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_module_info();
  inline void clear_has_module_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pb::GxDB_Module* module_info_;
  ::google::protobuf::uint32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Module_Buy_Gain_Mode_Res* default_instance_;
};
// -------------------------------------------------------------------

class GS2C_Building_Update : public ::google::protobuf::Message {
 public:
  GS2C_Building_Update();
  virtual ~GS2C_Building_Update();

  GS2C_Building_Update(const GS2C_Building_Update& from);

  inline GS2C_Building_Update& operator=(const GS2C_Building_Update& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GS2C_Building_Update& default_instance();

  void Swap(GS2C_Building_Update* other);

  // implements Message ----------------------------------------------

  GS2C_Building_Update* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GS2C_Building_Update& from);
  void MergeFrom(const GS2C_Building_Update& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 module_id = 1;
  inline bool has_module_id() const;
  inline void clear_module_id();
  static const int kModuleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 module_id() const;
  inline void set_module_id(::google::protobuf::uint32 value);

  // optional .pb.GxDB_Building building_info = 2;
  inline bool has_building_info() const;
  inline void clear_building_info();
  static const int kBuildingInfoFieldNumber = 2;
  inline const ::pb::GxDB_Building& building_info() const;
  inline ::pb::GxDB_Building* mutable_building_info();
  inline ::pb::GxDB_Building* release_building_info();
  inline void set_allocated_building_info(::pb::GxDB_Building* building_info);

  // @@protoc_insertion_point(class_scope:pb.GS2C_Building_Update)
 private:
  inline void set_has_module_id();
  inline void clear_has_module_id();
  inline void set_has_building_info();
  inline void clear_has_building_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pb::GxDB_Building* building_info_;
  ::google::protobuf::uint32 module_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Module_2eproto();
  friend void protobuf_AssignDesc_Module_2eproto();
  friend void protobuf_ShutdownFile_Module_2eproto();

  void InitAsDefaultInstance();
  static GS2C_Building_Update* default_instance_;
};
// ===================================================================


// ===================================================================

// GxDB_Module

// optional uint32 module_id = 1;
inline bool GxDB_Module::has_module_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GxDB_Module::set_has_module_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GxDB_Module::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GxDB_Module::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 GxDB_Module::module_id() const {
  return module_id_;
}
inline void GxDB_Module::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// optional uint32 gain_mode = 2;
inline bool GxDB_Module::has_gain_mode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GxDB_Module::set_has_gain_mode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GxDB_Module::clear_has_gain_mode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GxDB_Module::clear_gain_mode() {
  gain_mode_ = 0u;
  clear_has_gain_mode();
}
inline ::google::protobuf::uint32 GxDB_Module::gain_mode() const {
  return gain_mode_;
}
inline void GxDB_Module::set_gain_mode(::google::protobuf::uint32 value) {
  set_has_gain_mode();
  gain_mode_ = value;
}

// optional uint64 expire_time = 3;
inline bool GxDB_Module::has_expire_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GxDB_Module::set_has_expire_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GxDB_Module::clear_has_expire_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GxDB_Module::clear_expire_time() {
  expire_time_ = GOOGLE_ULONGLONG(0);
  clear_has_expire_time();
}
inline ::google::protobuf::uint64 GxDB_Module::expire_time() const {
  return expire_time_;
}
inline void GxDB_Module::set_expire_time(::google::protobuf::uint64 value) {
  set_has_expire_time();
  expire_time_ = value;
}

// optional bool is_rebuild = 4;
inline bool GxDB_Module::has_is_rebuild() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GxDB_Module::set_has_is_rebuild() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GxDB_Module::clear_has_is_rebuild() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GxDB_Module::clear_is_rebuild() {
  is_rebuild_ = false;
  clear_has_is_rebuild();
}
inline bool GxDB_Module::is_rebuild() const {
  return is_rebuild_;
}
inline void GxDB_Module::set_is_rebuild(bool value) {
  set_has_is_rebuild();
  is_rebuild_ = value;
}

// optional uint64 gain_start_time = 5;
inline bool GxDB_Module::has_gain_start_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GxDB_Module::set_has_gain_start_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GxDB_Module::clear_has_gain_start_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GxDB_Module::clear_gain_start_time() {
  gain_start_time_ = GOOGLE_ULONGLONG(0);
  clear_has_gain_start_time();
}
inline ::google::protobuf::uint64 GxDB_Module::gain_start_time() const {
  return gain_start_time_;
}
inline void GxDB_Module::set_gain_start_time(::google::protobuf::uint64 value) {
  set_has_gain_start_time();
  gain_start_time_ = value;
}

// optional uint32 gain_value = 6;
inline bool GxDB_Module::has_gain_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GxDB_Module::set_has_gain_value() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GxDB_Module::clear_has_gain_value() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GxDB_Module::clear_gain_value() {
  gain_value_ = 0u;
  clear_has_gain_value();
}
inline ::google::protobuf::uint32 GxDB_Module::gain_value() const {
  return gain_value_;
}
inline void GxDB_Module::set_gain_value(::google::protobuf::uint32 value) {
  set_has_gain_value();
  gain_value_ = value;
}

// -------------------------------------------------------------------

// GxDB_Building

// optional uint32 building_id = 1;
inline bool GxDB_Building::has_building_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GxDB_Building::set_has_building_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GxDB_Building::clear_has_building_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GxDB_Building::clear_building_id() {
  building_id_ = 0u;
  clear_has_building_id();
}
inline ::google::protobuf::uint32 GxDB_Building::building_id() const {
  return building_id_;
}
inline void GxDB_Building::set_building_id(::google::protobuf::uint32 value) {
  set_has_building_id();
  building_id_ = value;
}

// optional uint32 building_lv = 2;
inline bool GxDB_Building::has_building_lv() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GxDB_Building::set_has_building_lv() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GxDB_Building::clear_has_building_lv() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GxDB_Building::clear_building_lv() {
  building_lv_ = 0u;
  clear_has_building_lv();
}
inline ::google::protobuf::uint32 GxDB_Building::building_lv() const {
  return building_lv_;
}
inline void GxDB_Building::set_building_lv(::google::protobuf::uint32 value) {
  set_has_building_lv();
  building_lv_ = value;
}

// optional uint64 lvup_start_time = 3;
inline bool GxDB_Building::has_lvup_start_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GxDB_Building::set_has_lvup_start_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GxDB_Building::clear_has_lvup_start_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GxDB_Building::clear_lvup_start_time() {
  lvup_start_time_ = GOOGLE_ULONGLONG(0);
  clear_has_lvup_start_time();
}
inline ::google::protobuf::uint64 GxDB_Building::lvup_start_time() const {
  return lvup_start_time_;
}
inline void GxDB_Building::set_lvup_start_time(::google::protobuf::uint64 value) {
  set_has_lvup_start_time();
  lvup_start_time_ = value;
}

// optional bool is_rebuild = 4;
inline bool GxDB_Building::has_is_rebuild() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GxDB_Building::set_has_is_rebuild() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GxDB_Building::clear_has_is_rebuild() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GxDB_Building::clear_is_rebuild() {
  is_rebuild_ = false;
  clear_has_is_rebuild();
}
inline bool GxDB_Building::is_rebuild() const {
  return is_rebuild_;
}
inline void GxDB_Building::set_is_rebuild(bool value) {
  set_has_is_rebuild();
  is_rebuild_ = value;
}

// -------------------------------------------------------------------

// GxDB_Modules_Info

// repeated .pb.GxDB_Module module_arr = 1;
inline int GxDB_Modules_Info::module_arr_size() const {
  return module_arr_.size();
}
inline void GxDB_Modules_Info::clear_module_arr() {
  module_arr_.Clear();
}
inline const ::pb::GxDB_Module& GxDB_Modules_Info::module_arr(int index) const {
  return module_arr_.Get(index);
}
inline ::pb::GxDB_Module* GxDB_Modules_Info::mutable_module_arr(int index) {
  return module_arr_.Mutable(index);
}
inline ::pb::GxDB_Module* GxDB_Modules_Info::add_module_arr() {
  return module_arr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Module >&
GxDB_Modules_Info::module_arr() const {
  return module_arr_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Module >*
GxDB_Modules_Info::mutable_module_arr() {
  return &module_arr_;
}

// -------------------------------------------------------------------

// GxDB_Buildings_Info

// repeated .pb.GxDB_Building building_arr = 1;
inline int GxDB_Buildings_Info::building_arr_size() const {
  return building_arr_.size();
}
inline void GxDB_Buildings_Info::clear_building_arr() {
  building_arr_.Clear();
}
inline const ::pb::GxDB_Building& GxDB_Buildings_Info::building_arr(int index) const {
  return building_arr_.Get(index);
}
inline ::pb::GxDB_Building* GxDB_Buildings_Info::mutable_building_arr(int index) {
  return building_arr_.Mutable(index);
}
inline ::pb::GxDB_Building* GxDB_Buildings_Info::add_building_arr() {
  return building_arr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >&
GxDB_Buildings_Info::building_arr() const {
  return building_arr_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >*
GxDB_Buildings_Info::mutable_building_arr() {
  return &building_arr_;
}

// -------------------------------------------------------------------

// C2GS_Building_State

// optional uint32 module_id = 1;
inline bool C2GS_Building_State::has_module_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2GS_Building_State::set_has_module_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2GS_Building_State::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2GS_Building_State::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 C2GS_Building_State::module_id() const {
  return module_id_;
}
inline void C2GS_Building_State::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// -------------------------------------------------------------------

// GS2C_Building_State

// optional .pb.GxDB_Module module = 1;
inline bool GS2C_Building_State::has_module() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Building_State::set_has_module() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Building_State::clear_has_module() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Building_State::clear_module() {
  if (module_ != NULL) module_->::pb::GxDB_Module::Clear();
  clear_has_module();
}
inline const ::pb::GxDB_Module& GS2C_Building_State::module() const {
  return module_ != NULL ? *module_ : *default_instance_->module_;
}
inline ::pb::GxDB_Module* GS2C_Building_State::mutable_module() {
  set_has_module();
  if (module_ == NULL) module_ = new ::pb::GxDB_Module;
  return module_;
}
inline ::pb::GxDB_Module* GS2C_Building_State::release_module() {
  clear_has_module();
  ::pb::GxDB_Module* temp = module_;
  module_ = NULL;
  return temp;
}
inline void GS2C_Building_State::set_allocated_module(::pb::GxDB_Module* module) {
  delete module_;
  module_ = module;
  if (module) {
    set_has_module();
  } else {
    clear_has_module();
  }
}

// repeated .pb.GxDB_Building building_state = 2;
inline int GS2C_Building_State::building_state_size() const {
  return building_state_.size();
}
inline void GS2C_Building_State::clear_building_state() {
  building_state_.Clear();
}
inline const ::pb::GxDB_Building& GS2C_Building_State::building_state(int index) const {
  return building_state_.Get(index);
}
inline ::pb::GxDB_Building* GS2C_Building_State::mutable_building_state(int index) {
  return building_state_.Mutable(index);
}
inline ::pb::GxDB_Building* GS2C_Building_State::add_building_state() {
  return building_state_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >&
GS2C_Building_State::building_state() const {
  return building_state_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::GxDB_Building >*
GS2C_Building_State::mutable_building_state() {
  return &building_state_;
}

// optional uint32 remain_auto_times = 3;
inline bool GS2C_Building_State::has_remain_auto_times() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GS2C_Building_State::set_has_remain_auto_times() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GS2C_Building_State::clear_has_remain_auto_times() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GS2C_Building_State::clear_remain_auto_times() {
  remain_auto_times_ = 0u;
  clear_has_remain_auto_times();
}
inline ::google::protobuf::uint32 GS2C_Building_State::remain_auto_times() const {
  return remain_auto_times_;
}
inline void GS2C_Building_State::set_remain_auto_times(::google::protobuf::uint32 value) {
  set_has_remain_auto_times();
  remain_auto_times_ = value;
}

// -------------------------------------------------------------------

// C2GS_Building_Level_Up

// required bool is_auto = 1;
inline bool C2GS_Building_Level_Up::has_is_auto() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2GS_Building_Level_Up::set_has_is_auto() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2GS_Building_Level_Up::clear_has_is_auto() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2GS_Building_Level_Up::clear_is_auto() {
  is_auto_ = false;
  clear_has_is_auto();
}
inline bool C2GS_Building_Level_Up::is_auto() const {
  return is_auto_;
}
inline void C2GS_Building_Level_Up::set_is_auto(bool value) {
  set_has_is_auto();
  is_auto_ = value;
}

// optional uint32 building_id = 2;
inline bool C2GS_Building_Level_Up::has_building_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2GS_Building_Level_Up::set_has_building_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2GS_Building_Level_Up::clear_has_building_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2GS_Building_Level_Up::clear_building_id() {
  building_id_ = 0u;
  clear_has_building_id();
}
inline ::google::protobuf::uint32 C2GS_Building_Level_Up::building_id() const {
  return building_id_;
}
inline void C2GS_Building_Level_Up::set_building_id(::google::protobuf::uint32 value) {
  set_has_building_id();
  building_id_ = value;
}

// optional uint32 module_id = 3;
inline bool C2GS_Building_Level_Up::has_module_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void C2GS_Building_Level_Up::set_has_module_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void C2GS_Building_Level_Up::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void C2GS_Building_Level_Up::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 C2GS_Building_Level_Up::module_id() const {
  return module_id_;
}
inline void C2GS_Building_Level_Up::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// -------------------------------------------------------------------

// GS2C_Building_Level_Up_Begin_lv_up_info

// optional uint32 building_id = 1;
inline bool GS2C_Building_Level_Up_Begin_lv_up_info::has_building_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::set_has_building_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::clear_has_building_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::clear_building_id() {
  building_id_ = 0u;
  clear_has_building_id();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up_Begin_lv_up_info::building_id() const {
  return building_id_;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::set_building_id(::google::protobuf::uint32 value) {
  set_has_building_id();
  building_id_ = value;
}

// optional uint64 lvup_start_time = 2;
inline bool GS2C_Building_Level_Up_Begin_lv_up_info::has_lvup_start_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::set_has_lvup_start_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::clear_has_lvup_start_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::clear_lvup_start_time() {
  lvup_start_time_ = GOOGLE_ULONGLONG(0);
  clear_has_lvup_start_time();
}
inline ::google::protobuf::uint64 GS2C_Building_Level_Up_Begin_lv_up_info::lvup_start_time() const {
  return lvup_start_time_;
}
inline void GS2C_Building_Level_Up_Begin_lv_up_info::set_lvup_start_time(::google::protobuf::uint64 value) {
  set_has_lvup_start_time();
  lvup_start_time_ = value;
}

// -------------------------------------------------------------------

// GS2C_Building_Level_Up_Begin

// optional uint32 module_id = 1;
inline bool GS2C_Building_Level_Up_Begin::has_module_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Building_Level_Up_Begin::set_has_module_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Building_Level_Up_Begin::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Building_Level_Up_Begin::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up_Begin::module_id() const {
  return module_id_;
}
inline void GS2C_Building_Level_Up_Begin::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// optional uint32 remain_auto_times = 2;
inline bool GS2C_Building_Level_Up_Begin::has_remain_auto_times() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GS2C_Building_Level_Up_Begin::set_has_remain_auto_times() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GS2C_Building_Level_Up_Begin::clear_has_remain_auto_times() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GS2C_Building_Level_Up_Begin::clear_remain_auto_times() {
  remain_auto_times_ = 0u;
  clear_has_remain_auto_times();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up_Begin::remain_auto_times() const {
  return remain_auto_times_;
}
inline void GS2C_Building_Level_Up_Begin::set_remain_auto_times(::google::protobuf::uint32 value) {
  set_has_remain_auto_times();
  remain_auto_times_ = value;
}

// repeated .pb.GS2C_Building_Level_Up_Begin.lv_up_info build_state = 3;
inline int GS2C_Building_Level_Up_Begin::build_state_size() const {
  return build_state_.size();
}
inline void GS2C_Building_Level_Up_Begin::clear_build_state() {
  build_state_.Clear();
}
inline const ::pb::GS2C_Building_Level_Up_Begin_lv_up_info& GS2C_Building_Level_Up_Begin::build_state(int index) const {
  return build_state_.Get(index);
}
inline ::pb::GS2C_Building_Level_Up_Begin_lv_up_info* GS2C_Building_Level_Up_Begin::mutable_build_state(int index) {
  return build_state_.Mutable(index);
}
inline ::pb::GS2C_Building_Level_Up_Begin_lv_up_info* GS2C_Building_Level_Up_Begin::add_build_state() {
  return build_state_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up_Begin_lv_up_info >&
GS2C_Building_Level_Up_Begin::build_state() const {
  return build_state_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up_Begin_lv_up_info >*
GS2C_Building_Level_Up_Begin::mutable_build_state() {
  return &build_state_;
}

// -------------------------------------------------------------------

// GS2C_Building_Level_Up

// required uint32 building_id = 1;
inline bool GS2C_Building_Level_Up::has_building_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Building_Level_Up::set_has_building_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Building_Level_Up::clear_has_building_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Building_Level_Up::clear_building_id() {
  building_id_ = 0u;
  clear_has_building_id();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up::building_id() const {
  return building_id_;
}
inline void GS2C_Building_Level_Up::set_building_id(::google::protobuf::uint32 value) {
  set_has_building_id();
  building_id_ = value;
}

// required uint32 module_id = 2;
inline bool GS2C_Building_Level_Up::has_module_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GS2C_Building_Level_Up::set_has_module_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GS2C_Building_Level_Up::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GS2C_Building_Level_Up::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up::module_id() const {
  return module_id_;
}
inline void GS2C_Building_Level_Up::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// required uint32 building_lv = 3;
inline bool GS2C_Building_Level_Up::has_building_lv() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GS2C_Building_Level_Up::set_has_building_lv() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GS2C_Building_Level_Up::clear_has_building_lv() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GS2C_Building_Level_Up::clear_building_lv() {
  building_lv_ = 0u;
  clear_has_building_lv();
}
inline ::google::protobuf::uint32 GS2C_Building_Level_Up::building_lv() const {
  return building_lv_;
}
inline void GS2C_Building_Level_Up::set_building_lv(::google::protobuf::uint32 value) {
  set_has_building_lv();
  building_lv_ = value;
}

// -------------------------------------------------------------------

// GS2C_Building_Gold_Hammer

// repeated .pb.GS2C_Building_Level_Up building_lv_up = 1;
inline int GS2C_Building_Gold_Hammer::building_lv_up_size() const {
  return building_lv_up_.size();
}
inline void GS2C_Building_Gold_Hammer::clear_building_lv_up() {
  building_lv_up_.Clear();
}
inline const ::pb::GS2C_Building_Level_Up& GS2C_Building_Gold_Hammer::building_lv_up(int index) const {
  return building_lv_up_.Get(index);
}
inline ::pb::GS2C_Building_Level_Up* GS2C_Building_Gold_Hammer::mutable_building_lv_up(int index) {
  return building_lv_up_.Mutable(index);
}
inline ::pb::GS2C_Building_Level_Up* GS2C_Building_Gold_Hammer::add_building_lv_up() {
  return building_lv_up_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up >&
GS2C_Building_Gold_Hammer::building_lv_up() const {
  return building_lv_up_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::GS2C_Building_Level_Up >*
GS2C_Building_Gold_Hammer::mutable_building_lv_up() {
  return &building_lv_up_;
}

// -------------------------------------------------------------------

// GS2C_Module_Buy_Gain_Mode_Res

// required uint32 error_code = 1;
inline bool GS2C_Module_Buy_Gain_Mode_Res::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::clear_error_code() {
  error_code_ = 0u;
  clear_has_error_code();
}
inline ::google::protobuf::uint32 GS2C_Module_Buy_Gain_Mode_Res::error_code() const {
  return error_code_;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::set_error_code(::google::protobuf::uint32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional .pb.GxDB_Module module_Info = 2;
inline bool GS2C_Module_Buy_Gain_Mode_Res::has_module_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::set_has_module_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::clear_has_module_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::clear_module_info() {
  if (module_info_ != NULL) module_info_->::pb::GxDB_Module::Clear();
  clear_has_module_info();
}
inline const ::pb::GxDB_Module& GS2C_Module_Buy_Gain_Mode_Res::module_info() const {
  return module_info_ != NULL ? *module_info_ : *default_instance_->module_info_;
}
inline ::pb::GxDB_Module* GS2C_Module_Buy_Gain_Mode_Res::mutable_module_info() {
  set_has_module_info();
  if (module_info_ == NULL) module_info_ = new ::pb::GxDB_Module;
  return module_info_;
}
inline ::pb::GxDB_Module* GS2C_Module_Buy_Gain_Mode_Res::release_module_info() {
  clear_has_module_info();
  ::pb::GxDB_Module* temp = module_info_;
  module_info_ = NULL;
  return temp;
}
inline void GS2C_Module_Buy_Gain_Mode_Res::set_allocated_module_info(::pb::GxDB_Module* module_info) {
  delete module_info_;
  module_info_ = module_info;
  if (module_info) {
    set_has_module_info();
  } else {
    clear_has_module_info();
  }
}

// -------------------------------------------------------------------

// GS2C_Building_Update

// required uint32 module_id = 1;
inline bool GS2C_Building_Update::has_module_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GS2C_Building_Update::set_has_module_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GS2C_Building_Update::clear_has_module_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GS2C_Building_Update::clear_module_id() {
  module_id_ = 0u;
  clear_has_module_id();
}
inline ::google::protobuf::uint32 GS2C_Building_Update::module_id() const {
  return module_id_;
}
inline void GS2C_Building_Update::set_module_id(::google::protobuf::uint32 value) {
  set_has_module_id();
  module_id_ = value;
}

// optional .pb.GxDB_Building building_info = 2;
inline bool GS2C_Building_Update::has_building_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GS2C_Building_Update::set_has_building_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GS2C_Building_Update::clear_has_building_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GS2C_Building_Update::clear_building_info() {
  if (building_info_ != NULL) building_info_->::pb::GxDB_Building::Clear();
  clear_has_building_info();
}
inline const ::pb::GxDB_Building& GS2C_Building_Update::building_info() const {
  return building_info_ != NULL ? *building_info_ : *default_instance_->building_info_;
}
inline ::pb::GxDB_Building* GS2C_Building_Update::mutable_building_info() {
  set_has_building_info();
  if (building_info_ == NULL) building_info_ = new ::pb::GxDB_Building;
  return building_info_;
}
inline ::pb::GxDB_Building* GS2C_Building_Update::release_building_info() {
  clear_has_building_info();
  ::pb::GxDB_Building* temp = building_info_;
  building_info_ = NULL;
  return temp;
}
inline void GS2C_Building_Update::set_allocated_building_info(::pb::GxDB_Building* building_info) {
  delete building_info_;
  building_info_ = building_info;
  if (building_info) {
    set_has_building_info();
  } else {
    clear_has_building_info();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Module_2eproto__INCLUDED
