#pragma once

enum LOTTERY_TYPE{
    LOTTERY_SILVER  = 0,
    LOTTERY_GOLD    = 1,
    LOTTERY_EVENT   = 2,
    LOTTERY_NORMAL_MAX,

    LOTTERY_FIRST_SOLU_0   = 100,
    LOTTERY_FIRST_SOLU_1,
    LOTTERY_FIRST_SOLU_2,
    LOTTERY_FIRST_MAX,
};

enum EQUIP_PURIFY_TYPE
{
	FREE_PURIFY = 0,
	KING_PURIFY = 1
};
