
HandleOpcode(CMSG_COMBAT_BEGIN);
HandleOpcode(CMSG_COMBAT_SELECT_TACTIC);
HandleOpcode(CMSG_COMBAT_UNWATCH);
HandleOpcode(CMSG_COMBAT_ATTRACT_ENEMY);
HandleOpcode(CMSG_COMBAT_RUSH);
HandleOpcode(CMSG_COMBAT_RUNAWAY);
HandleOpcode(CMSG_COMBAT_ADD_SOLDIER);
HandleOpcode(CMSG_COMBAT_CALL_UP);
HandleOpcode(CMSG_COMBAT_SPEED_UP);
HandleOpcode(CMSG_COMBAT_ADD_HERO);
HandleOpcode(CMSG_COMBAT_CALL_REQUEST);
HandleOpcode(CMSG_COMBAT_ANI_FINISHED);
HandleOpcode(CMSG_COMBAT_TRY);
HandleOpcode(CMSG_AUTO_COMBAT);
HandleOpcode(CMSG_QUICK_COMBAT);
HandleOpcode(CMSG_GET_HERO_STATUS);
HandleOpcode(CMSG_COMBAT_REQUEST_NEXT_LST);
HandleOpcode(CMSG_COMBAT_REQUEST_TERR);

HandleOpcode(CMSG_CRUSADE_BACK);
HandleOpcode(CMSG_GET_MY_SHADOW_NUM);