// PlayerNetPackOpcodes.h

HandleOpcode(CMSG_PALACE_ALL_INFO);
HandleOpcode(CMSG_PALACE_FIGHT_NEW_OFFICE);
HandleOpcode(CMSG_PALACE_CANCEL_OFFICE);
HandleOpcode(CMSG_PALACE_APPLY_AIDE);
HandleOpcode(CMSG_PALACE_CANCEL_AIDE);
HandleOpcode(CMSG_PALACE_CANCEL_APPLY_AIDE);
HandleOpcode(CMSG_PALACE_AGREE_AIDE);
HandleOpcode(CMSG_PALACE_REFUSE_AIDE);
HandleOpcode(CMSG_PALACE_FIRE_AIDE);
HandleOpcode(CMSG_PALACE_TAKE_SALARY);

HandleOpcode(CMSG_PALACE_SKILL_FLY_TO);
HandleOpcode(CMSG_PALACE_SKILL_EMPTY);
HandleOpcode(CMSG_PALACE_SKILL_CONFUSE);
HandleOpcode(CMSG_PALACE_SKILL_MAZE);
HandleOpcode(CMSG_PALACE_SKILL_TRAP);

HandleOpcode(CMSG_PALACE_LEVEL_INFO);
HandleOpcode(CMSG_PALACE_TAKE_REWARD);