// PlayerNetPackOpcodes.h

HandleOpcode(CMSG_SMITHY_ALL_INFO);
HandleOpcode(CMSG_SMITHY_SMELTER_DO);
HandleOpcode(CMSG_SMITHY_SUB_SMELTER_LEVELUP);
HandleOpcode(CMSG_SMITHY_BUILD_BY_TOKEN);
HandleOpcode(CMSG_SMITHY_BUILD_BY_SILVER);
HandleOpcode(CMSG_SMITHY_LEVELUP_TO_OPEN_SUB_SMELTER);
