// PlayerNetPackOpcodes.h

HandleOpcode(CMSG_ALTAR_ALL_INFO);
HandleOpcode(CMSG_ALTAR_STUDY);
HandleOpcode(CMSG_ALTAR_TAKE_REWARD);
HandleOpcode(CMSG_ALTAR_SUB_ALTAR_LEVELUP);
HandleOpcode(CMSG_ALTAR_BUILD_BY_TOKEN);
HandleOpcode(CMSG_ALTAR_BUILD_BY_SILVER);
HandleOpcode(CMSG_ALTAR_LEVELUP_TO_OPEN_SUB_ALTAR);
HandleOpcode(CMSG_ALTAR_STUDY_ONEKEY);
HandleOpcode(CMSG_ALTAR_TAKE_REWARD_ONEKEY);
